[2025-10-02T18:04:33.989+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_scd2.load_to_dw_scd2 manual__2025-10-02T18:01:08.857695+00:00 [queued]>
[2025-10-02T18:04:34.035+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_scd2.load_to_dw_scd2 manual__2025-10-02T18:01:08.857695+00:00 [queued]>
[2025-10-02T18:04:34.036+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-02T18:04:34.118+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_dw_scd2> on 2025-10-02 18:01:08.857695+00:00
[2025-10-02T18:04:34.138+0000] {standard_task_runner.py:60} INFO - Started process 1557 to run task
[2025-10-02T18:04:34.147+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_scd2', 'load_to_dw_scd2', 'manual__2025-10-02T18:01:08.857695+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/process_scripts.py', '--cfg-path', '/tmp/tmptwgdh7t5']
[2025-10-02T18:04:34.166+0000] {standard_task_runner.py:88} INFO - Job 69: Subtask load_to_dw_scd2
[2025-10-02T18:04:34.327+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-02T18:04:34.774+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_pipeline_scd2.load_to_dw_scd2 manual__2025-10-02T18:01:08.857695+00:00 [running]> on host f327b3c387fa
[2025-10-02T18:04:35.647+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_scd2' AIRFLOW_CTX_TASK_ID='load_to_dw_scd2' AIRFLOW_CTX_EXECUTION_DATE='2025-10-02T18:01:08.857695+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-02T18:01:08.857695+00:00'
[2025-10-02T18:04:40.445+0000] {scd2_loader.py:194} INFO - Processing file: Country_code.xlsx
[2025-10-02T18:04:45.885+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process_scripts.py", line 28, in run_scd2_loader
    load_all_out_files_to_dw()
  File "/opt/airflow/dags/scd2_loader.py", line 210, in load_all_out_files_to_dw
    df = _normalize_df_columns(df)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scd2_loader.py", line 49, in _normalize_df_columns
    return df.fillna(None)
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 7156, in fillna
    value, method = validate_fillna_kwargs(value, method)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/util/_validators.py", line 293, in validate_fillna_kwargs
    raise ValueError("Must specify a fill 'value' or 'method'.")
ValueError: Must specify a fill 'value' or 'method'.
[2025-10-02T18:04:45.955+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_pipeline_scd2, task_id=load_to_dw_scd2, execution_date=20251002T180108, start_date=20251002T180433, end_date=20251002T180445
[2025-10-02T18:04:46.009+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 69 for task load_to_dw_scd2 (Must specify a fill 'value' or 'method'.; 1557)
[2025-10-02T18:04:46.103+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-02T18:04:46.154+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
