[2025-09-27T17:40:21.357+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dynamic_process_scripts_dag.run_processor_extract_country manual__2025-09-27T17:40:14.285972+00:00 [queued]>
[2025-09-27T17:40:21.422+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dynamic_process_scripts_dag.run_processor_extract_country manual__2025-09-27T17:40:14.285972+00:00 [queued]>
[2025-09-27T17:40:21.425+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-27T17:40:21.537+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_processor_extract_country> on 2025-09-27 17:40:14.285972+00:00
[2025-09-27T17:40:21.609+0000] {standard_task_runner.py:60} INFO - Started process 206 to run task
[2025-09-27T17:40:21.679+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dynamic_process_scripts_dag', 'run_processor_extract_country', 'manual__2025-09-27T17:40:14.285972+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/process_scripts.py', '--cfg-path', '/tmp/tmpkrz0n6r1']
[2025-09-27T17:40:21.752+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask run_processor_extract_country
[2025-09-27T17:40:22.007+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-27T17:40:22.700+0000] {task_command.py:423} INFO - Running <TaskInstance: dynamic_process_scripts_dag.run_processor_extract_country manual__2025-09-27T17:40:14.285972+00:00 [running]> on host 70d7caa3f6a3
[2025-09-27T17:40:23.931+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dynamic_process_scripts_dag' AIRFLOW_CTX_TASK_ID='run_processor_extract_country' AIRFLOW_CTX_EXECUTION_DATE='2025-09-27T17:40:14.285972+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-27T17:40:14.285972+00:00'
[2025-09-27T17:40:33.403+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process_scripts.py", line 34, in <lambda>
    python_callable=lambda s=script_path: subprocess.run(['python', str(s)], check=True)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/airflow/scripts/processor_extract_country.py']' returned non-zero exit status 1.
[2025-09-27T17:40:33.525+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dynamic_process_scripts_dag, task_id=run_processor_extract_country, execution_date=20250927T174014, start_date=20250927T174021, end_date=20250927T174033
[2025-09-27T17:40:33.618+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task run_processor_extract_country (Command '['python', '/opt/airflow/scripts/processor_extract_country.py']' returned non-zero exit status 1.; 206)
[2025-09-27T17:40:33.683+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-27T17:40:33.772+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
